### ISSUE TITLE
ColorCodedLogs ios11 is broken.

### ISSUE THREAD

**Issue by ljh9961** [leftyfl1p/ColorCodedLogs#2]
colorcodedlogs does not work properly on iOS 11 When you tap the Phone app, the Phone app is turned off; if you click it again, the Phone app will still work, but recent calls lists will appear in black text.

**Comment by laoyur** [comment]
looks like hook `com.apple.mobilephone` doesn't work on iOS 11.3.1, the tweak not loaded at all. don't know why
